### ISSUE TITLE
Error trying to use texify.

### ISSUE THREAD

**Issue by redbobcat** [maxima-project-on-github/maxima-packages#15]
This is what I can see :(
```
(%o0)                                done
(%i1) load("texify.lisp")$

(%i2) texify(diff(f(x),x));

Maxima encountered a Lisp error:

 Condition in FORMAT [or a callee]: INTERNAL-SIMPLE-ERROR: Format error: illegal directive.
                                 V
"\[~*~:[~;~:*(~:/nullfix/)\; ~]~:/nullfix/\]"

Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
(%i3) 
```

**Comment by robert-dodier** [comment]
From the form of the message, I gather that you are working with Maxima built with GCL. It appears that GCL does not implement one of the formatting operations which is specified for Common Lisp, namely Tilde Slash. I've reported this as a bug to the GCL project: https://savannah.gnu.org/bugs/index.php?56868

My advice is to try to work with Maxima built with another Lisp implementation, such as SBCL. There are other bugs in GCL, so although it is some inconvenience to switch to another Lisp, I think it's a win overall. If you want some advice about working with SBCL or another Lisp, please feel free to ask on the Maxima mailing list. See: https://sourceforge.net/projects/maxima/lists/maxima-discuss

Thank you for raising this issue. I'm closing it now since it's a bug in GCL and not in texify.

**Comment by alpchelintsev** [comment]
I automate my calculations using in Maxima package. My program generates a file with commands for the package and through I/O redirection and works with it. https://github.com/alpchelintsev/periodic_sols/blob/master/maxima.cpp
 
My Project: https://github.com/alpchelintsev/periodic_sols
